- name: copy myuac.xml
  template:
    src: myuac.xml
    dest: /

- name: create pythonmonitor
  file: 
    path: /pythonmonitor
    state: directory

- name: copy monitor.py
  template:
    src: monitor.py
    dest: /pythonmonitor

- name: create /etc/collectd
  file: 
    path: /etc/collectd
    state: directory

- name: copy collectd.conf
  template:
    src: collectd.conf
    dest: /etc/collectd/

- name: add kafka.lm to hosts
  become: yes
  shell: "echo {{ almip }} kafka.lm >> /etc/hosts"
