heat_template_version: "2018-08-31"
description: "Base infrastructure for Brownfield Demo"

resources:
  voip_net: 
    type: "OS::Neutron::Net"
    properties: 
      admin_state_up: true
      name: voip_net

  voip_subnet: 
    type: "OS::Neutron::Subnet"
    properties: 
      network: { get_resource: voip_net }
      name: voip_subnet
      enable_dhcp: true
      dns_nameservers:
        - 8.8.8.8
      cidr: "192.168.100.0/24"

  voip_security_group: 
    type: "OS::Neutron::SecurityGroup"
    properties: 
      rules:
        - port_range_min: 1
          port_range_max: 65535
          protocol: udp 
        - port_range_min: 1
          port_range_max: 65535
          protocol: tcp
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
      name: voip-security-group

  voip_router:
    type: "OS::Neutron::Router"
    properties: 
      admin_state_up: true
      name: voip_router
      external_gateway_info:
        network: "public"

  voip_routerinterface: 
    type: "OS::Neutron::RouterInterface"
    properties: 
      router: { get_resource: voip_router }
      subnet: { get_resource: voip_subnet }

outputs:
  network_id: 
    value: { get_resource: voip_net }
  subnet_id: 
    value: { get_resource: voip_subnet }
  security_group_id: 
    value: { get_resource: voip_security_group }
