heat_template_version: "2018-08-31"
description: "Base infrastructure for Brownfield Demo"

resources:
  voip_net: 
    type: "OS::Neutron::Net"
    properties: 
      admin_state_up: true
      name: voip_net

  voip_subnet: 
    type: "OS::Neutron::Subnet"
    properties: 
      network: { get_resource: voip_net }
      name: voip_subnet
      enable_dhcp: true
      dns_nameservers:
        - 8.8.8.8
      cidr: "192.168.100.0/24"

  voip_security_group: 
    type: "OS::Neutron::SecurityGroup"
    properties: 
      rules:
        - port_range_min: 1
          port_range_max: 65535
          protocol: udp 
        - port_range_min: 1
          port_range_max: 65535
          protocol: tcp
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
      name: voip-security-group

  voip_router:
    type: "OS::Neutron::Router"
    properties: 
      admin_state_up: true
      name: voip_router
      external_gateway_info:
        network: "public"

  voip_routerinterface: 
    type: "OS::Neutron::RouterInterface"
    properties: 
      router: { get_resource: voip_router }
      subnet: { get_resource: voip_subnet }

  asterisk_port: 
    type: "OS::Neutron::Port"
    properties: 
      admin_state_up: true
      fixed_ips: [{ "subnet": { get_resource: voip_subnet}}]
      security_groups: 
        - { get_resource: voip_security_group }
      name: asterisk-port
      network: { get_resource: voip_net }

  asterisk_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: "public"
      port_id: { get_resource: asterisk_port }

  asterisk: 
    type: "OS::Nova::Server"
    properties: 
      networks: 
        - port: { get_resource: asterisk_port }
      name: asterisk
      flavor: m1.small
      key_name: default
      image:  ip-pbx
      config_drive: true
      user_data_format: RAW
      user_data: |
        #cloud-config
        manage_etc_hosts: true
        bootcmd: 
         - [ sysctl, net.ipv4.ip_forward=1 ]
         - [ sh, -c, echo 'nameserver 8.8.8.8' > /etc/resolv.conf ]
        ssh_pwauth: True
        password: ubuntu
        chpasswd:
          list: |
            ubuntu:ubuntu
          expire: False
        packages:
          - voip

  sipp_port: 
    type: "OS::Neutron::Port"
    properties: 
      admin_state_up: true
      fixed_ips: [{ "subnet": { get_resource: voip_subnet}}]
      security_groups: 
        - { get_resource: voip_security_group }
      name: sipp-port
      network: { get_resource: voip_net }

  sipp_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: "public"
      port_id: { get_resource: sipp_port }

  sipp: 
    type: "OS::Nova::Server"
    properties: 
      networks: 
        - port: { get_resource: sipp_port }
      name: sipp
      flavor: m1.small
      key_name: default
      image:  sipp
      config_drive: true
      user_data_format: RAW
      user_data: |
        #cloud-config
        manage_etc_hosts: true
        bootcmd: 
         - [ sysctl, net.ipv4.ip_forward=1 ]
         - [ sh, -c, echo 'nameserver 8.8.8.8' > /etc/resolv.conf ]
        ssh_pwauth: True
        password: ubuntu
        chpasswd:
          list: |
            ubuntu:ubuntu
          expire: False
        packages:
          - voip

outputs:
  asterisk_ip: 
    value: { get_attr: [ asterisk_floating_ip , floating_ip_address ] }
  sipp_ip: 
    value: { get_attr: [ sipp_floating_ip , floating_ip_address ] }
