heat_template_version: "2018-08-31"
description: "Base infrastructure for Brownfield Demo"

resources:

  adopt_net: 
    type: "OS::Neutron::Net"
    properties: 
      admin_state_up: true
      name: adopt_net

  adopt_subnet: 
    type: "OS::Neutron::Subnet"
    properties: 
      network: { get_resource: adopt_net }
      name: adopt_subnet
      enable_dhcp: true
      dns_nameservers:
        - 8.8.8.8
      cidr: "192.168.10.0/24"

  adopt_router:
    type: "OS::Neutron::Router"
    properties: 
      admin_state_up: true
      name: adopt_router
      external_gateway_info:
        network: "public"

  adopt_port: 
    type: "OS::Neutron::Port"
    properties: 
      admin_state_up: true
      fixed_ips: [{ "subnet": { get_resource: adopt_subnet}}]
      security_groups: 
        - default
      name: adopt-port
      network: { get_resource: adopt_net }

  adopt: 
    type: "OS::Nova::Server"
    properties: 
      networks: 
        - port: { get_resource: adopt_port }
      name: adopt
      flavor: m1.small
      key_name: default
      image:  bionic-server-cloudimg-amd64
      config_drive: true
      user_data_format: RAW
      user_data: |
        #cloud-config
        manage_etc_hosts: true
        bootcmd: 
         - [ sysctl, net.ipv4.ip_forward=1 ]
         - [ sh, -c, echo 'nameserver 8.8.8.8' > /etc/resolv.conf ]
        ssh_pwauth: True
        password: ubuntu
        chpasswd:
          list: |
            ubuntu:ubuntu
          expire: False

  adopt_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: "public"
      port_id: { get_resource: adopt_port }

outputs:
  host: 
    value: { get_attr: [ adopt_floating_ip , floating_ip_address ] }
