---


- name: Configure Lifecycle Transition
  hosts: resource
  gather_facts: False
  become: true

  tasks:
  - name: check if myuac file exists
    stat: 
      path: /myuac.xml
    register: myuac_file
  
  - name: copy myuac.xml
    copy:
      src: ./config/myuac.xml
      dest: /
    when: myuac_file.stat.exists != true

  - name: check if pythonmonitor file exists
    stat: 
      path: /pythonmonitor/monitor.py
    register: pythonmonitor_file

  - name: create pythonmonitor
    file: 
      path: /pythonmonitor
      state: directory
    when: pythonmonitor_file.stat.exists != true

  - name: copy monitor.py
    template:
      src: ./config/monitor.py
      dest: /pythonmonitor/
    when: pythonmonitor_file.stat.exists != true

  - name: check if collectd file exists
    stat: 
      path: /etc/collectd/collectd.conf
    register: collectd_file

  - name: create /etc/collectd
    file: 
      path: /etc/collectd
      state: directory
    when: collectd_file.stat.exists != true

  - name: copy collectd.conf
    copy:
      src: ./config/collectd.conf
      dest: /etc/collectd/collectd.conf
    when: collectd_file.stat.exists != true
      

  - name: add kafka.lm to hosts
    lineinfile:
      path: /etc/hosts
      line: "{{ dl_properties.almip }} kafka.lm"
