--- 

- hosts: asterisk-vm
  gather_facts: no
  become: yes
  tasks:
    - import_role:
        name: asterisk

- hosts: sipp-vm
  gather_facts: no
  become: yes
  tasks:
    - import_role:
        name: sipp
