---
- name: Install
  hosts: all
  gather_facts: False
  become: true
  
  tasks: 
 
    - name: Wait for update to finish
      shell: |
        systemctl disable --now apt-daily.timer
        systemctl disable --now apt-daily-upgrade.timer
        systemctl daemon-reload
        systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true
        apt-get -y purge unattended-upgrades 

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present
        update_cache: true        

    - name: Create workspace
      file:
        path: /tmp/adopt
        state: directory
        mode: '0755'

    - name: Copy stack transformer
      copy:
        src: files/stacktransformer/
        dest: /tmp/adopt

    - name: Install stack transformer
      shell: python3 -m pip install /tmp/adopt

    - name: Template deployment location
      template:
        src: files/deployment-location.yaml
        dest: /tmp/adopt/deployment-location.yaml
        mode: '0755'
    
    - name: Copy Heat template (asterisk)
      copy: 
        src: files/heat-templates/asterisk-resource.yaml
        dest: /tmp/adopt/asterisk-resource.yaml
        mode: '0755'

    - name: Copy Heat template (shared)
      copy: 
        src: files/heat-templates/shared-resource.yaml
        dest: /tmp/adopt/shared-resource.yaml
        mode: '0755'

    - name: Copy Heat template (sipp)
      copy: 
        src: files/heat-templates/sipp-resource.yaml
        dest: /tmp/adopt/sipp-resource.yaml
        mode: '0755'

    - name: Copy transform file
      copy:
        src: files/transform.yaml
        dest: /tmp/adopt/transform.yaml
        mode: '0755'
    
    - name: Run transformer
      shell: python3 /tmp/adopt/run.py {{ properties['old_stack_id'] }} /tmp/adopt/transform.yaml /tmp/adopt/deployment-location.yaml
      register: transform_output

    - set_fact:
        stack_ids: "{{ transform_output.stdout | from_yaml }}"

    - debug:
        msg: "{{stack_ids}}"

    - name: Return stack_ids as outputs
      set_fact:
        output__asterisk_stack_id: "{{stack_ids['asterisk']}}"
        output__sipp_stack_id: "{{stack_ids['sipp']}}"
        output__shared_stack_id: "{{stack_ids['shared']}}"
