heat_template_version: 2013-05-23

description: >
  Basic example to deploy a single VM

parameters:
  key_name:
    type: string
    default: default
  image:
    type: string
    default: bionic-server-cloudimg-amd64
resources:
  serverB:
    type: OS::Nova::Server
    properties:
      flavor: m1.small
      user_data_format: SOFTWARE_CONFIG
      image:
        get_param: image
      key_name:
        get_param: key_name
      networks:
      - port: { get_resource: serverB_port }
  serverB_port:
    type: OS::Neutron::Port
    properties:
      network: voice_net
outputs:
  serverB_ip:
    value:
      get_attr:
      - serverB
      - networks
      - voice_net
      - 0
    description: The private IP address of the server
