- name: copy extensions
  template:
    src: extensions.conf
    dest: /etc/asterisk/extensions.conf
    owner: root
    group: root
    mode: 0644

- name: write the sip config file
  template:
    src: sip.conf.template
    dest: /etc/asterisk/sip.conf

- name: create pythonmonitor
  file: 
    path: /pythonmonitor
    state: directory

- name: copy monitor.py
  template:
    src: pythonmonitor/monitor.py
    dest: /pythonmonitor/

- name: create /etc/collectd
  file: 
    path: /etc/collectd
    state: directory

- name: copy collectd.conf
  template:
    src: collectd.conf
    dest: /etc/collectd/collectd.conf
    
- name: add kafka.lm to hosts
  shell: "echo {{ almip }} kafka.lm >> /etc/hosts"


