---

- name: Configure Lifecycle Transition
  hosts: resource
  gather_facts: False
  become: true

  tasks:
  - name: pause
    shell: python --version

  - name: set the stack_id to null
    set_fact: 
      output__stack_id: "0"