---

- name: Configure Lifecycle Transition
  hosts: resource
  gather_facts: False
  become: true

  vars: 
    bindIP: "{{ properties.voice_ip_address }}"
  tasks:
  - name: copy
    copy:
      src: ./config/extensions.conf
      dest: /etc/asterisk/extensions.conf
      owner: root
      group: root
      mode: 0644
    when: properties.stack_id is not defined or properties.stack_id|length==0

  - name: write the sip config file
    template:
      src: ./config/sip.conf.template
      dest: /etc/asterisk/sip.conf
    when: properties.stack_id is not defined or properties.stack_id|length==0

  - name: create pythonmonitor
    file: 
      path: /pythonmonitor
      state: directory
    when: properties.stack_id is not defined or properties.stack_id|length==0

  - name: copy monitor.py
    template:
      src: ./config/pythonmonitor/monitor.py
      dest: /pythonmonitor/
    when: properties.stack_id is not defined or properties.stack_id|length==0

  - name: create /etc/collectd
    file: 
      path: /etc/collectd
      state: directory
    when: properties.stack_id is not defined or properties.stack_id|length==0

  - name: copy collectd.conf
    copy:
      src: ./config/collectd.conf
      dest: /etc/collectd/collectd.conf
    when: properties.stack_id is not defined or properties.stack_id|length==0
      
  - name: add kafka.lm to hosts
    shell: "echo {{ dl_properties.almip }} kafka.lm >> /etc/hosts"
    when: properties.stack_id is not defined or properties.stack_id|length==0


